### ISSUE TITLE
Symbol source from apt packages

### ISSUE THREAD

**Issue by mikepurvis** [getsentry/symbolicator#102]
I'd like to be able to have Symbolicator grab symbols from remote apt endpoints. I have two use-cases for this:

- The `dbgsym` packages available from Debian, which are named `lib[foo]-dbgsym_[version]_[arch].deb`, eg: http://debug.mirrors.debian.org/debian-debug/pool/main/b/boost1.67/
- Some internally-generated symbol packages stored in an an apt repo which are simply named `debug-[buildid]_0_[arch].deb`.

Both of these could be covered by an external server which exposed the Microsoft Symbol Server API to Symbolicator, and that was my first instinct for how to address this, but then it occurred to me that it might work to have an `apt` source built right in. Basically, you would give the source information (URL, component, etc), and then supply one or more printf-style templates for package names to look for symbols in. The packages would be expected to contain a single `.debug` file, optionally compressed, which is the gdb symbols to use.

I'd imagine the configuration looking something like:

```
  {
    "id": "debian-sid-symbols",
    "type": "apt",
    "source": {
      "url": "http://debug.mirrors.debian.org/debian-debug",
      "dist": "sid-debug",
      "components": ["main"]
    },
    "schemas": "%{libname}-dbgsym_%{libver}_%{arch}"
  },
```

I would expect the implementation to use libapt bindings (eg https://docs.rs/apt-pkg-native), and then download and unpack locally with dpkg in a temporary directory.

I'm happy to work on this if there's interest from the maintainers and I can get a bit more design guidance. If not, I can definitely achieve what I need to with a small Flask server sitting outside of Symbolicator.

**Comment by jan-auer** [comment]
Great idea, and as it turns out we've been thinking about this, too. The hardest part about this is to know which package to download ahead of time. Since the required information (especially the library version and name as used in the apt package) is not available in a structured form, Symbolicator might have to guess or download speculatively. At least to my understanding, getting the version number for loaded images is not reliable in many cases, but I can try to investigate this more. 

However, if one knows which versions would be required ahead, it would be totally feasible to put them in a compatible structure for Symbolicator to grab.

This repository includes a tool called `symsorter`. It can scan through a directory or archive containing debug files and organizes them into a compatible bucket. At the moment, it only works for iOS symbols, but could easily be extended to work for linux as well, or even download from apt automatically.

At Sentry, we were thinking of doing this for common packages and system libraries, so that these symbols are available out-of-the box.

**Comment by mikepurvis** [comment]
Yeah, I was looking at the various file directory structure options, and the main issue for me is just that at my org we have hundreds of thousands of symbol files, and they're already stored in apt packages. The main reason for this is just that it makes it easy for any dev to quickly install the required symbols onto their workstation or the target device in order to do interactive gdb sessions. A secondary reason is that the apt structure makes it trivial to prune symbols that are no longer needed, for example when a test build has aged out.

So we really, really don't want to pay that full storage cost a second time by pre-loading everything into Sentry; it needs to be an on-demand/caching model, which is why I'm excited about Symbolicator.

My primary interest is actually the second scenario that's easier and more unique to me, where the buildid is part of the package name, and there are no versions— that one should be quite easy to get working, since you know exactly what to grab just from information in the stack trace.

For the other scenario, debian maps library names directly to package names, so I think the main thing there is just needing to get the exact versions of those library packages from the target so that the correct dbgsym package versions can be fetched. In theory that shouldn't be too hard to do, but it's a) something that has to happen on the target, so it's more metadata for Sentry/Sentrypad to have to collect, and b) it's pretty specific to the Debian/Ubuntu ecosystem, which is also a bummer.

**Comment by mikepurvis** [comment]
It's a bit of a goofy approach, but for a released distro, one approach to dbgsym debs might be simply to guess that it's the newest version of [lib]-dbgsym available in the archive, and if that has the wrong buildid, download progressively older versions until the correct one is found or we run out or give up. Typically there is only one version (or a small number) of each lib in a given distro anyway.

**Comment by mitsuhiko** [comment]
The big question is where to get `libver` from. From what I can tell you can't get that from the information within the crash. I also don't think sentry could go into the business of rehosting debug files because of the traffic that would require. That said I was just made aware of how nixos solves this (#103 for more information) and they basically have a mapping that goes from build id to archive.

We could potentially do that by regularly fetching all debug archives from debian/ubuntu and building up an index and hosting that. (Though ideally debian/ubuntu would do that).

That way one could hit something like `http://indexurl.invalid/buildid/HEXADECIMAL-BUILD-ID` and get back a JSON document with the URL of where the archive is that contains that build ID, the file format of the archive and the path within the archive.

**Comment by mitsuhiko** [comment]
So I just noticed that debian actually has something that can act as an index here which is pretty neat.  The packages list has build IDs for almost all packages. Example from `stable-debug`:

```
Package: 0ad-dbgsym
Source: 0ad
Version: 0.0.23.1-2
Installed-Size: 134624
Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>
Architecture: amd64
Replaces: 0ad-dbg (<< 0.0.20-2~)
Depends: 0ad (= 0.0.23.1-2)
Breaks: 0ad-dbg (<< 0.0.20-2~)
Description: debug symbols for 0ad
Auto-Built-Package: debug-symbols
Build-Ids: 21956d3f6ca06eb488785ebfd388516a48d370a6 7e065602b2704fd21dd8fb0118c540ad55d09b65 8c10a839c61f0042393526e5909667b44ffb9dba 949d87cb1495c0aaf544a85fd359981abf9d520f f2ce0fd4d5767b0d0bdede1559fe2b4ac77217bf
Description-md5: 0f09ddda1685998c794e3597c9232cb2
Section: debug
Priority: optional
Filename: pool/main/0/0ad/0ad-dbgsym_0.0.23.1-2_amd64.deb
Size: 132824148
SHA256: f926e3393fecfa6fa76cba9dac8f4df3a32f96df55fccc492fed7e6aff3304fb
```

This is awesome. We could refetch these files in regular intervals and then get the package name that contains the debug file. We could then also use that archive to fetch the source to get the binary. Definitely something to investigate. Sadly ubuntu does not index the build IDs so this would only work for debian.

**Comment by mitsuhiko** [comment]
For testing purposes I built a script that creates a somewhat functional index. Ideally such an index could be hosted by debian but we could probably get someone else to host it if needed: https://gist.github.com/mitsuhiko/ee8f506445e06679b32934bc04c8d5b2

I could not find find all .deb archives for all .ddeb ones which is a bit annoying but most seem to be there. Also for the non .ddeb archives one would need to enumerate all files and look for the build id since they are not indexed within the archive :(

**Comment by mikepurvis** [comment]
How likely is it that a built-in apt source for Symbolicator would be configurable enough to also cover my custom-generated buildid packages? If it's going to be fairly focused on the upsteam debian story (which is totally reasonable, of course), I may resume building an external server to feed my symbols in via the MSS API. I think I'd prefer that route than having to patch in that functionality and build Symbolicator from source until the end of time. :)

**Comment by mitsuhiko** [comment]
@mikepurvis right now I would say it depends. I'm currently trying to figure out what a good approach is. From where I stand no matter what the outcome the best we can wish for right now is a `buildid -> debug / non debug package` mapping but that means in one such archive there is more than one debug information file stored.

So we likely need a new abstraction in symbolicator that can fetch those extra debug files out as well to prevent downloading the same archive over and over again. Once we have that abstraction I can see multiple ways in which this can be handled.

The most obvious one would be to support the official debian sources directly through some sort of secondary index we build nightly out of the build id information in the `Packages` file (unless debian provides this out of the box). Secondarily however we could add a package source which just shells out to a process which could be invoked with the build id and then needs to figure out itself how to get it. At that point this could be fairly easy to handle.

I'm definitely interested in getting support for linux distributions in but ideally we can find at least some solution that is applicable to multiple people.

**Comment by jernejstrasner** [comment]
This issue is stale. Closing. Please reopen if necessary.
