### ISSUE TITLE
Special-case webpack in js frame paths

### ISSUE THREAD

**Issue by loewenheim** [getsentry/symbolicator#1142]
The sentry monolith has code to massage the filenames of js frames coming from webpack. This should be ported to Symbolicator.

**Comment by Swatinem** [comment]
Is this related to just webpack, or is that about url-joining in general? If so, we might need to really do some custom logic to join urls, or we just accept that urls are not supposed to start with `../`?

**Comment by loewenheim** [comment]
I think it might be both. The Python code relating to webpack that I mean is [here](https://github.com/getsentry/sentry/blob/687e93a4ed78ccb4d3c90b57906cd12212f2dffd/src/sentry/lang/javascript/processor.py#L1576).

**Comment by Swatinem** [comment]
I believe this was already being fixed by https://github.com/getsentry/symbolicator/pull/1145, with more followups in https://github.com/getsentry/symbolicator/pull/1149 and https://github.com/getsentry/symbolicator/pull/1150.

I also opened https://github.com/getsentry/symbolicator/issues/1151 with some more discussion points.
