### ISSUE TITLE
Debug Information File uploaded but not applied to event.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/symbolicator#1539]
Sentry is failing to apply a debug file to event. The file was uploaded 3 days before the event was accepted and is valid according to the Sentry CLI. Reprocessing the event has no effect. 

There are no [errors raised while processing the file.](https://sentry.my.sentry.io/organizations/sentry/discover/homepage/?end=2024-10-15T23%3A59%3A59&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All%20Events&project=5&query=object_id.debug_id%3Afa659095-a556-430d-bf09-e74af5c50c17-1&sort=-timestamp&start=2024-10-13T00%3A00%3A00&utc=true&yAxis=count%28%29)

![Image](https://github.com/user-attachments/assets/32d3af1d-efbc-446d-a87a-317d4bff869a)

Due to possible PII involved, more information on the issue is available in this [internal ticket](https://sentry.zendesk.com/agent/tickets/135139)

**Comment by loewenheim** [comment]
I can reproduce this locally, and I'm pretty sure I know what's happening.

They are trying to symbolicate a .NET event with a native Windows .pdb file (the file they uploaded). Unfortunately we currently don't support this case, although we would like to—see https://github.com/getsentry/symbolic/issues/871.

Here are the steps that happen to cause this behavior:
1. Symbolicator receives an event with an image of type `pe_dotnet` and debug id `<DEBUG_ID>` inside. That makes sense because it's a .NET event.
2. Symbolicator asks Sentry for a portable pdb file with debug id `<DEBUG_ID>. It specifically requests a portable pdb because that is the only debug file format we support for .NET events.
3. Sentry replies that it doesn't have a portable pdb file with debug id `<DEBUG_ID>`, which is true—the uploaded file is a Windows PDB file!
4. Symbolicator returns the event and reports that the portable pdb file couldn't be found.
5. Sentry receives Symbolicator's reply and sees that it couldn't find the file with debug id `<DEBUG_ID>`. But it has a file with that debug id! So it thinks that the file must have been uploaded _after_ symbolication, even though that's clearly not true.

Of course, reprocessing cannot fix this. It's unfortunate that our error message is so confusing in this case; we'll have to think about improving that even independent of actually supporting the feature.

The only suggestion I can make in the meantime is to compile with `DebugType` `portable`, as explained [here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#debugtype). That will use the portable pdb format, which we support for .NET.
