### ISSUE TITLE
Failed to symbolicate big so file

### ISSUE THREAD

**Issue by hulucc** [getsentry/symbolicator#163]
The so file size is 1.1g. I can't find any further detail about why its failed. Please help.

Symbolicator log
```
symbolicator-0 symbolicator 2020-01-07T12:57:03Z [symbolicator::server] INFO: Starting http server:
 0.0.0.0:3021
symbolicator-0 symbolicator 2020-01-07T12:57:03Z [actix_net::server::server] INFO: Starting 4 worke
rs
symbolicator-0 symbolicator 2020-01-07T12:57:03Z [actix_net::server::server] INFO: Starting server 
on 0.0.0.0:3021
symbolicator-0 symbolicator 2020-01-07T12:57:03Z [symbolicator::server] INFO: Starting system      
symbolicator-0 symbolicator 2020-01-07T13:00:06Z [symbolicator::actors::symcaches] WARN: Failed to 
write symcache: failed to parse object
```

**Comment by hulucc** [comment]
For anyone may encounter similar problem, I solved this by converting symbol to breakpad format before upload to sentry. It seems breadpad symbol has a better support to symbolicate minidump for now.

**Comment by Swatinem** [comment]
We have no real size limit on debug files, but the error `Failed to write symcache: failed to parse object` looks like we hit an error parsing the file somewhere. It would be interesting to figure out why exactly it failed (or if the failure was fixed in the meantime).

While switching to breakpad symbol files might be a shortterm solution; those files are suboptimal for a number of reasons and you should always prefer to use the original debug files directly.

If this is still a concern, please try again using the original files, and if that does not work, please file an issue over at https://github.com/getsentry/symbolic
