### ISSUE TITLE
Symsorter overwrites "meta" file

### ISSUE THREAD

**Issue by dizer** [getsentry/symbolicator#200]
Let's say I have a directory with 2 Windows files:

```
PS C:\debug> dir ./unsorted


    Directory: C:\debug\unsorted


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         3/9/2020   4:12 AM      126614528 chrome.dll
-a----         3/9/2020   4:13 AM     2476789760 chrome.dll.pdb
```

If I will sort chrome.dll only:

```
PS C:\debug> ./symsorter.exe  -bundle-id win --output ./sorted-mini --prefix win_release_x64 ./unsorted/chrome.dll
chrome.dll (x86_64) -> ./sorted-mini\win_release_x64\26/020e92257781134c4c44205044422e1/executable

Done: sorted 1 debug files
```

then `26/020e92257781134c4c44205044422e1/meta` will contain:

```
{"name":"chrome.dll","arch":"x86_64","file_format":"pe"}
```

But if I will specify `chrome.dll.pdb` instead of `chrome.dll`:

```
PS C:\debug> ./symsorter.exe  -bundle-id win --output ./sorted-mini --prefix win_release_x64 ./unsorted/chrome.dll.pdb
chrome.dll.pdb (x86_64) -> ./sorted-mini\win_release_x64\26/020e92257781134c4c44205044422e1/debuginfo

Done: sorted 1 debug files
```

then the same file `26/020e92257781134c4c44205044422e1/meta` will contain:

```
{"name":"chrome.dll.pdb","arch":"x86_64","file_format":"pdb"}
```

======

We using symsorter for preparing debug symbols S3 repository and this "swallow" problem sometimes (depending on sort order) makes some .pdbs unavailable.

**Comment by mitsuhiko** [comment]
This indeed seems suboptimal. That said the `meta` file is unused by symbolicator so you should still find the PDB for symbolication purposes.

**Comment by jan-auer** [comment]
@dizer could you elaborate why this makes the PDB unavailable? You're right that the meta file gets overwritten, where it should get merged instead. However you should end up with the following folder structure:

```
26/
|- 020e92257781134c4c44205044422e1/
   |- debuginfo
   |- executable
```

What is a bit strange, is that the paths contain both slashes and backslashes in your output. Might that cause the issue?

**Comment by dizer** [comment]
Hi @jan-auer, slashes messed up on Windows but seem like it is working as expected. 

About my problem: I need to generate the filename for the SSQP directory layout (like `filename/hash2/hash/filename`). This filename I take from the `meta` file. The problem is its dependency on the sorting order - it can be `chrome.dll.pdb` or `chrome.dll`. 

```
# chrome.dll sorted last
# {"name":"chrome.dll","arch":"x86_64","file_format":"pe"}
chrome.dll/26/020e92257781134c4c44205044422e1/chrome.dll

# chrome.dll.pdb sorted last
# {"name":"chrome.dll.pdb","arch":"x86_64","file_format":"pdb"}
chrome.dll.pdb/26/020e92257781134c4c44205044422e1/chrome.dll.pdb
```

In most cases `chrome.dll` sorted before `chrome.dll.pdb` and it's not an issue but in our case, we have a copy of `chrome.dll` in a subdirectory. We sorting `chrome.dll`, `chrome.dll.pdb` and  `chrome.dll` again. So we lose metainformation about the PDB file and can't generate the path for SSQP layout.

I didn't try the new universal directory layout, maybe it doesn't have this problem. Also, we can try to sort *.pdb files only as a walkaround. But seems like the root problem is a bug.

**Comment by jan-auer** [comment]
I see. The issue here is that while `symbolicator` supports SSQP conventions, symsorter does not (yet). For this reason, I'm afraid that symsorter may not be the right tool for doing this. 

If you create this S3 bucket only for the use with Sentry, then you can just leave the directory structure you received from symsorter. It is the [Unified Layout](https://getsentry.github.io/symbolicator/advanced/symbol-server-compatibility/#unified-symbol-server-layout) which has the advantage that it does not require filenames for symbol lookups.

If you do need SSQP for other tools, I think we have two possible options here:
1. We could add SSQP and other directory layouts for symsorter. 
2. We should make the `meta` file aware of a `code_file` and `debug_file`, like everything else in the system.

Also, note that [SSQP paths](https://github.com/dotnet/symstore/blob/master/docs/specs/SSQP_Key_Conventions.md#pdb-signature-age) do not create folders for the first two characters of the signature. Your paths would actually be:

```
chrome.dll/26020e92257781134c4c44205044422e1/chrome.dll
chrome.dll.pdb/26020e92257781134c4c44205044422e1/chrome.dll.pdb
```
