### ISSUE TITLE
0.3.1 Failed to demangle unknown identifier

### ISSUE THREAD

**Issue by mk4437** [getsentry/symbolicator#320]
Today we upgraded from a quite old version of symbolicator to 0.3.1 and have received several dozen errors saying "Failed to demangle unknown identifier".   We're processing Android and iOS crashes.  

Is this something for us to be concerned about?

**Comment by mk4437** [comment]
Correction, we're only using symbolicator for iOS.

**Comment by Swatinem** [comment]
This is nothing really to be concerned about.

These should be resolved to the function names in your stack trace. If you deem that those don’t contain sensitive information, you might as well share the failed identifiers and we can look at those case-by-case.

Also, obj-c identifiers are something we don’t handle correctly as of now, otherwise some newer and not widely used c++20 features might lack support.

**Comment by mk4437** [comment]
Thanks.  In that case, I suppose I can set this to ignore in Sentry?
