### ISSUE TITLE
Special case failing to load `linux-vdso.so.1`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/symbolicator#328]
With crashpad on Linux we'll always have this error and no actionable way to fix it:

![image](https://user-images.githubusercontent.com/1633368/103232761-4ec50480-4909-11eb-9ed9-4c638412964b.png)

We should hide this error.

**Comment by jan-auer** [comment]
@bruno-garcia can you share an otherwise fully symbolicated stack trace with CFI applied that shows a frame pointing into the vDSO? 

---

It looks like it's usually not expected to get symbols for the vDSO, so even in GCC, the warning was suppressed at some point. See https://sourceware.org/legacy-ml/gdb-patches/2012-11/msg00604.html. That said, for server side symbolication symbols would still be required to compute a proper stack trace. [`man vdso(7)`](https://man7.org/linux/man-pages/man7/vdso.7.html#DESCRIPTION) even explains that the symbols are theoretically available.

There should be a `-dbgsym` package that ships the library, which should be sufficient to provide CFI and a symbol table. 

---

If we want to detect and suppress this message, we should consider doing this in Sentry. The name of the virtual object differs by architecture and is one of:

```
       aarch64    linux-vdso.so.1
       arm        linux-vdso.so.1
       ia64       linux-gate.so.1
       mips       linux-vdso.so.1
       ppc/32     linux-vdso32.so.1
       ppc/64     linux-vdso64.so.1
       riscv      linux-vdso.so.1
       s390       linux-vdso32.so.1
       s390x      linux-vdso64.so.1
       sh         linux-gate.so.1
       i386       linux-gate.so.1
       x86-64     linux-vdso.so.1
       x86/x32    linux-vdso.so.1
```

**Comment by bruno-garcia** [comment]
https://sentry.io/organizations/sentry-sdks/issues/2117494000/?project=5572891&query=is%3Aunresolved

There was another where I uploaded all OS symbols manually to test it out, and only `linux-vdso.so.1` errored out. I spent a bit of time looking for it in the OS :)

**Comment by jan-auer** [comment]
There are many things going on in this stack trace. Let's break this down, I think there will have to be a number of fixes:

- The top two frames do not point into a mapped range, which leads me to believe that the image map is broken. That this comes from a Breakpad minidump complicates things.
- `main` should by default cut off the stack trace at the bottom. There's little point in showing frames below.
- Even though the main image has unwind information, the next frame is stack scanned. 
- the vDSO is always a system library, so we should classify it as such. That would also suppress the above error.
- It is possible to get vDSO symbols for some linux distros, although it's not straight forward. In all cases that I'm aware of, that requires to pull kernel debug symbols manually. I'm not sure how that would look like for Android.

**Comment by bruno-garcia** [comment]
> That this comes from a Breakpad minidump complicates things.

It's using crashpad.

> the vDSO is always a system library, so we should classify it as such. That would also suppress the above error.

👍

**Comment by bruno-garcia** [comment]
Haven't seen this issue in a while
