### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by mk4437** [getsentry/symbolicator#346]
On 0.3.1 when under heavy load we've been getting "too many open files" errors on downloads and when writing to symcache.  Our current open files limit is 1024.  Do you have a recommended limit for production?

**Comment by mitsuhiko** [comment]
I believe we’re running at 4096.

**Comment by flub** [comment]
Yes, 1024 is too low for the current design, 4096 is a much better choice.

Internally we're a bit wasteful with filedescriptors currently, and we can and do want to improve on this.  But the road to getting there is going to take a while, partially because it copes just fine when bumping this limit so it's not overly pressing.

**Comment by mk4437** [comment]
Thanks to you both.  I will recommend we set to 4096.
