### ISSUE TITLE
Allow custom AWS region

### ISSUE THREAD

**Issue by brancz** [getsentry/symbolicator#447]
I would like to run symbolicator against a [minio](https://min.io/) object storage, but the way the [configuration works today](https://github.com/getsentry/symbolicator/blob/b32b7a414e6dabe6fff5e3b1bd32513d48b89524/crates/symbolicator/src/sources.rs#L161), it is not possible to specify a custom AWS region. [Rusoto is generally capable of this](https://github.com/rusoto/rusoto/blob/31cf1506f9f4bd7af7a1f86ced3cec436913d518/rusoto/signature/src/region.rs#L117-L124). If agreed to allow configuring this, it could be retrofitted without breaking the configuration using [string-or-struct](https://serde.rs/string-or-struct.html).

Let me know what you think, happy to contribute!

@jan-auer

**Comment by jan-auer** [comment]
@brancz absolutely!

Interestingly, the `Deserialize` implementation of `Region` mentions that they chose a tuple serialization because of a lack of "flatten", which has been added to serde since. I wonder if the intent was to flatten the region's custom attributes into the surrounding struct. 

Either way, string-or-struct deserialization sounds good and we'd be happy about a contribution. Thanks!
