### ISSUE TITLE
symsorter sorts some files into 00/000000

### ISSUE THREAD

**Issue by kristjanvalur** [getsentry/symbolicator#465]
### Environment

Windows, symsorter @ d7e43cb9fbe1e92f8f7c3b3dc9bbed1329f7a7c7

### Steps to Reproduce

Run symsorter on some _so files (attached)

### Expected Result

Sorts into a proper hash or discartds

### Actual Result
It assigns debug info 00/000000 which clearly is nonsensical and just causes noise.

```
UE4Editor-Niagara.pdb (dbg, x86_64) -> symbols\77/c1454123ac4eab8237e1c8459a5e771/debuginfo
UE4Editor-NiagaraEditor.pdb (dbg, x86_64) -> symbols\1b/add497584049d7a0b80e23f8177e231/debuginfo
hdf5.dll (lib, x86_64) -> symbols\00/0000000000000000000000000000000/executable
UE4Editor-AlembicHairTranslatorModule.dll (lib, x86_64) -> symbols\5b/ddd381ba3e43f2850553832419ee351/executable
UE4Editor-AlembicHairTranslatorModule.pdb (dbg, x86_64) -> symbols\5b/ddd381ba3e43f2850553832419ee351/debuginfo
UE4Editor-RemoteImportLibrary.dll (lib, x86_64) -> symbols\4d/35b928af4949658ce43a6b0aadc2821/executable
UE4Editor-DatasmithRemoteImport.dll (lib, x86_64) -> symbols\14/8b0600610b4945b1c802860b8d4e691/executable
UE4Editor-DatasmithRemoteImport.pdb (dbg, x86_64) -> symbols\14/8b0600610b4945b1c802860b8d4e691/debuginfo
UE4Editor-RemoteImportLibrary.pdb (dbg, x86_64) -> symbols\4d/35b928af4949658ce43a6b0aadc2821/debuginfo
ar.dll (lib, x86_64) -> symbols\00/0000000000000000000000000000000/executable
boost_atomic-vc141-mt-x64-1_70.dll (lib, x86_64) -> symbols\00/0000000000000000000000000000000/executable
```

[hdf5 (2).zip](https://github.com/getsentry/symbolicator/files/6654410/hdf5.2.zip)

[boost_atomic-vc141-mt-gd-x64-1_70.zip](https://github.com/getsentry/symbolicator/files/6654405/boost_atomic-vc141-mt-gd-x64-1_70.zip)

**Comment by Swatinem** [comment]
I think we will have to check for a valid debug/code-id, and just silently drop objects that lack one.

On the other hand, it might be a good idea if you figure out why the dlls in question are lacking such id, because without it, we won’t be able to use it in symbolication at all, so crashes in/through those libraries will not be symbolicated correctly.

**Comment by kristjanvalur** [comment]
These are typically third party dlls.  I am gathering symbols from the
"plugins" folder of our UnrealEngine, and many of the plugins use such 3rd
party libraries.  We have no control over them, they might be stripped or
otherwise broken.  But we cannot easily skip them either.

þri., 15. jún. 2021 kl. 13:18 skrifaði Arpad Borsos <
***@***.***>:

**Comment by jan-auer** [comment]
There are really two issues here: 

1. Symsorter should output an error in such a case where the debug identifier cannot be computed. That error can then be skipped with `--ignore-errors`.
2. The debug identifier is computed by `symbolic` and there can be a multitude of reasons why that fails. To investigate this, we would need access to one of the files in question. ideally, we track that in a dedicated issue in the `getsentry/symbolic` repo.

**Comment by kristjanvalur** [comment]
Right, I uploaded two examples of failing files, what else do you need?

**Comment by jan-auer** [comment]
Sorry, I missed the links. We have everything we need, for now 👍

**Comment by jan-auer** [comment]
It looks like the DLLs you shared do not contain a CodeView PDB70 debugging information link, therefore we cannot compute a debug identifier. I will have to compare this with the Crashpad and Breakpad client implementations, since they might hash the code section.

By any chance, do you have a minidump from an application using the same build/version of one of these DLLs?

**Comment by kristjanvalur** [comment]
No, nothing yet.  This is from the "plugins" part of UnrealEngine and most of these plugins we don't actually have enabled in our game so never get loaded.  If there ever is a crash with such a debug ID I will let you know.

**Comment by jan-auer** [comment]
Many thanks to @relaxolotl for providing a swift fix! 🚀 

In the meanwhile, I checked Crashpad and it seems they also require the debug directory without a fallback ([code](https://github.com/chromium/crashpad/blob/cbec52f327fc9a98874e8f0ce522de274a7e8c22/snapshot/win/module_snapshot_win.cc#L66-L77)).

**Comment by relaxolotl** [comment]
I'll be closing this since #469 resolves the original issue. To sum things up, the supplied DLLs do not contain the info needed to derive a debug identifier, and Crashpad doesn't offer any alternative ways to compute a fallback identifier. When Crashpad bumps into these modules on their end it's assumed that there aren't any symbols available anyways, so we hit a dead-end there during symbolication.

I might have some of the details wrong here so if anybody notices anything off about what I've said feel free to chime in.

**Comment by kristjanvalur** [comment]
Thanks!
