### ISSUE TITLE
Unclear how to/if possible to use native ELF debug symbols on http source

### ISSUE THREAD

**Issue by dschmidt** [getsentry/symbolicator#522]
I'm trying to setup crash reporting for our new Linux AppImage in https://github.com/owncloud/client.
It works fine with breakpad symbols but we consider to switch to native ELF symbols for more stack unwinding goodness.

### Environment

We are hosting our symbols ourselves and use a http source on sentry.io.
We use breakpad directly to dump our crashes, no https://github.com/getsentry/sentry-native involved.

### Steps to Reproduce

To figure out filenames/urls I've setup a local symbolicator based on current master with this config:

```yml
bind: 127.0.0.1:3021
connect_to_reserved_ips: true
logging:
  level: debug
  format: pretty
  enable_backtraces: true

sources:
  - id: all
    type: http
    filters:
      filetypes: [elf_debug, elf_code]
    url: http://localhost:8082/
```

Unfortunately when I transmit a minidump to `symbolicator` like this:
```
http --form POST http://localhost:3021/minidump upload_file_minidump@/tmp/3d723194-87fa-c54a-49a4a018-05a02b9c.dmp
```

I don't see any requests to my http source:
```
./target/release/symbolicator run -c config.yml                                                                   
 INFO  symbolicator::server > Starting http server: 127.0.0.1:3021
 INFO  actix_net::server::server > Starting 32 workers
 INFO  actix_net::server::server > Starting server on 127.0.0.1:3021
 DEBUG symbolicator::services::symbolication > Processing minidump (382152 bytes)
```
That's all, no further output.

When I add `breakpad` to the list of filetypes I see requests in the symbolicator log when I transmit a minidump:
```
DEBUG symbolicator::services::download::http > Fetching debug file from http://localhost:8082/libxcb.so.1.1.0/0B46827C4EDDF5B38C32C422B6EFB4060/libxcb.so.1.1.0.sym
[...]
 DEBUG symbolicator::services::download            > Did not fetch debug file from Http(HttpRemoteDif { source: HttpSourceConfig { id: SourceId("all"), url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8082), path: "/", query: None, fragment: None }, headers: {}, files: CommonSourceConfig { filters: SourceFilters { filetypes: [Breakpad, ElfDebug, ElfCode], path_patterns: [] }, layout: DirectoryLayout { ty: Native, casing: Default }, is_public: false } }, location: SourceLocation("libxcb.so.1.1.0/0B46827C4EDDF5B38C32C422B6EFB4060/libxcb.so.1.1.0.sym") }): NotFound

```

... so `elf_debug` and `elf_code` seem to be recognized as valid options, but they still don't cause any requests being made afaict.

### Expected Result

There are requests for native elf symbols to my http source.

### Actual Result

I'm looking at 
https://getsentry.github.io/symbolicator/advanced/symbol-lookup.html
https://getsentry.github.io/symbolicator/advanced/symbol-server-compatibility.html
and can hardly make sense of it: http source is not explicitly mentioned and I'm not sure what I'm trying to do is actually supported while it looks like it's supported here:
https://getsentry.github.io/symbolicator/api/index.html

Looking at https://github.com/getsentry/symbolicator/blob/e4041b42abd8e5c6b39f50744606907eef070cd9/crates/symbolicator/src/utils/paths.rs#L125-L138
 it seems that in some condition `.debug` is added to binary filenames under some condition for `ElfCode`/`ElfDebug`, so I kind of expected that I would just see requests to e.g., 
```http://localhost:8082/libxcb.so.1.1.0/0B46827C4EDDF5B38C32C422B6EFB4060/libxcb.so.1.1.0.debug```,
but my rust foo is not strong enough to make real sense of the code there.

I'm attaching my `.dmp` file for easier debugging and to verify it's not an issue with our dump (zipped because GitHub doesn't allow `.dmp` files directly).
[3d723194-87fa-c54a-49a4a018-05a02b9c.dmp.zip](https://github.com/getsentry/symbolicator/files/7020577/3d723194-87fa-c54a-49a4a018-05a02b9c.dmp.zip)

Thanks in advance.

**Comment by jan-auer** [comment]
Thanks, I think there may be two unrelated issues in this conversation after taking a first glance. 

First, the source you specified is using the `"native"` layout by default, which uses GDB build-id directory paths for ELF. It looks like you're using the `"symstore"` layout, though, which you would have to set. The final log you received _"Did not fetch debug file from ..."_ indicates that symbolicator performed a lookup at a path and did not find the file on that path. We'll have a look at improving this message.

Regarding file filters, your configuration does indeed look correct on first glance and I think this may be a bug. While it should work like this, you can try to remove the filetype filters from the config to allow lookup of all file types. Possibly, the issue is connected to this -- we'll investigate.

Putting this together, can you try with this config:

```yaml
sources:
  - type: http
    id: all
    layout: symstore
    url: http://localhost:8082/
```

**Comment by dschmidt** [comment]
Hey @jan-auer 

thanks, for coming back to me!

> First, the source you specified is using the `"native"` layout by default, which uses GDB build-id directory paths for ELF. It looks like you're using the `"symstore"` layout, though, which you would have to set. The final log you received _"Did not fetch debug file from ..."_ indicates that symbolicator performed a lookup at a path and did not find the file on that path. We'll have a look at improving this message.

Well that message is pretty clear and also expected. There is no symbol at that path, but if I understand all of this correctly the lookup only happens when breakpad is enabled (and also `.sym` extension indicates) that this is a *breakpad* symbol lookup, which is working fine (when I provide the symbols at the respective path, this is just a debug setup to check the urls requested).

> Regarding file filters, your configuration does indeed look correct on first glance and I think this may be a bug. While it should work like this, you can try to remove the filetype filters from the config to allow lookup of all file types. Possibly, the issue is connected to this -- we'll investigate.

I removed all filters and still only see requets to those `.sym` urls, basically the exact same output as for `breakpad` being added to the list.


Now it gets interesting:

> Putting this together, can you try with this config:
> 
> ```yaml
> sources:
>   - type: http
>     id: all
>     layout: symstore
>     url: http://localhost:8082/
> ```

I think (and according to https://getsentry.github.io/symbolicator/api/index.html) the `layout` setting requires an object, so I tried it with:

```
sources:
  - type: http
    id: all
    layout:
      type: symstore
    url: http://localhost:8082/
```

That results in the same behavior as specifying
```
    filters:
      filetypes: [elf_debug, elf_code]
```
.i.e. no requests being made at all. Just:
```
 INFO  symbolicator::server > Starting http server: 127.0.0.1:3021
 INFO  actix_net::server::server > Starting 32 workers
 INFO  actix_net::server::server > Starting server on 127.0.0.1:3021
 DEBUG symbolicator::services::symbolication > Processing minidump (382152 bytes)
```

FWIW I updated to latest master before trying. Can you reproduce? Is there anything else I can provide you with?

**Comment by flub** [comment]
I was writing a unittest for the code that generates the lookup paths and noticed that for `elf_debug` and `elf_code` it only generates a lookup if the `symbolic::common::CodeId` is known.  The code_id in this case is extracted from the minidump in https://github.com/getsentry/symbolicator/blob/f2f594f509dfe4e8e9b67a3f4afdeacfada22819/crates/symbolicator/src/services/symbolication.rs#L556. I had a quick look at your minidump with `minidump_dump` and the `code_identifier` field of **all** your modules are set to just `id`.  This would mean e.g. `owncloud` and `libgio-2.0.so.0.6800.3` etc all would try and use the same debug file.
Furthermore this `code_id` is only 2 characters long, that would result in weird paths which might be filtered out somewhere.  I suspect this is done by breakpads code somehow since adding `dbg!()` around the `module.code_identifier()` call linked above and sending in your minidump results in lots of `[crates/symbolicator/src/services/symbolication.rs:556] module.code_identifier() = ""` and not a single valid code id.

So I think you'll have to figure out how to tell your compiler toolchain how to set valid code ids into your binaries before we can get any further.

**Comment by dschmidt** [comment]
According to https://develop.sentry.dev/sdk/event-payloads/debugmeta/:
```
ELF Images
[...]
   code_id
Optional. Identifier of the dynamic library or executable. If the program was compiled with a relatively recent compiler, this should be the hex representation of the NT_GNU_BUILD_ID program header (type PT_NOTE), or the value of the .note.gnu.build-id note section (type SHT_NOTE). Otherwise, leave this value empty.
```

```
readelf -Wn  usr/bin/owncloud

Displaying notes found in: .note.ABI-tag
  Owner                Data size        Description
  GNU                  0x00000010       NT_GNU_ABI_TAG (ABI version tag)            OS: Linux, ABI: 3.2.0

Displaying notes found in: .note.gnu.build-id
  Owner                Data size        Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)         Build ID: 9427c5bef0bc391b3b19fcd555b79faec75b48f3

```

Isn't that what we're after? Is maybe our breakpad version broken/too old?

**Comment by dschmidt** [comment]
FWIW we're using a standard GCC... 


Oh and thanks a lot for the investigation already 💪🏻

**Comment by flub** [comment]
> Displaying notes found in: .note.gnu.build-id
>   Owner                Data size        Description
>   GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)         Build ID: 9427c5bef0bc391b3b19fcd555b79faec75b48f3
> ```
> 
> Isn't that what we're after? Is maybe our breakpad version broken/too old?

Yep, that looks like what we need here.  So the compiler does fine but it still does not make it into the minidump.  Which indeed points towards checking your breakpad if that is what generates the minidump.

**Comment by Swatinem** [comment]
I’m a bit unsure if this issue was related to symbol server layout, or missing debug IDs in minidumps.

Either way, for symbol servers, I would recommend using our `symsorter` utility and `unified` symbol server layout. That should make sure symbols end up with the right naming. `symsorter` will also complain if symbols are missing proper debug ids.

Please reopen if this is still an issue.
